# Generated by Django 2.1.7 on 2019-03-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Очередь'), ('in_progress', 'В работе'), ('done', 'Сделано')], default='backlog', max_length=20),
        ),
    ]
